apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - namespace.yaml
  - ../../base/backend-api

namePrefix: staging-

configMapGenerator:
  - name: backend-api-config
    behavior: merge
    literals:
      - ui-color=#ffff00
      - log-level=info

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: backend-api
