apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - namespace.yaml
  - ../../base/backend-api

namePrefix: prod-

configMapGenerator:
  - name: backend-api-config
    behavior: merge
    literals:
      - ui-color=#0000ff
      - log-level=warn

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: backend-api
