apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
  annotations:
    # This records the initial "cause" in rollout history
    kubernetes.io/change-cause: "Initial deployment with Nginx 1.23.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # Standard for High Availability
      maxSurge: 1
  template:
    metadata:
      labels:
        app: v1
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"