apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/backend-api

# Add 'dev-' prefix
namePrefix: dev-

# dev-specific values
configMapGenerator:
  - name: backend-api-config
    behavior: merge
    literals:
      - ui-color=#00ff00
      - log-level=debug


patches:
  - path: replica-patch.yaml
  - path: resource-limits-dev.yaml
