apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

# Reference 
resources:
  - ../../base/backend-api

# 'dev-' prefix to all 
namePrefix: dev-

configMapGenerator:
  - name: backend-api-config
    behavior: merge
    literals:
      - ui-color=#00ff00
      - log-level=debug

patches:
  - target:
      kind: Deployment
      name: backend-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
